apiVersion: ENC[AES256_GCM,data:jHo=,iv:awdn8hqvA1juh7NfassrnqlhsvsNqiEQ+2Vl97gbO70=,tag:re8yn9IpEQEwpzo+9IshKA==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:mdYQrtwwsUY=,iv:tTodM4zq6DhZAytyZXjeFPVlny6qMsxl53VE1b4RzCk=,tag:6+8P+5bxSnaHiu8QSxITqg==,type:str]
    password: ENC[AES256_GCM,data:8wxAhkdxsfP/+H3D/WdprmYab/M=,iv:vdKkNdsDY15Nm6Xh8X491IeCkQWnxsSyRZzt29BPcNk=,tag:tXierml639q2xztkcV2wsg==,type:str]
kind: ENC[AES256_GCM,data:7fE+cDpz,iv:tW6rrMq4bciHVZbCGrv8McqK8yc6iximS465nBSXR84=,tag:iHgnX5jndv5U49L7Yq64jw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VjvyCyJAC/Lb2qGQ8/UU2aa0gvuu,iv:6OCSZTnr9S/aadxeHPvsCJj6cg5uePhN+Iadp801Vlc=,tag:d2zQ8GAnWQk/0rxNXn7mcw==,type:str]
    namespace: ENC[AES256_GCM,data:1ZzJG5FCNk7ht60=,iv:ImcHtiNNst0GTWUl8ZY3NFNSJc5d92+40nAxZ92EAE4=,tag:eGB42AUtM8oBKWJPu25fJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kw9pdzdc7s3t9yfjd39az62scaylhmq4ewaa8c9pjj23pjnsmqjszekaxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM3BCQjFYTllYRml3SWV5
            T2lFejNOSkZHSUcwMWt4ck1ENHprNklwcURJCks3QnVIWjJmb2c1QmdXM0x4R283
            SjJFV0JFT1lUeDF1aVlTWmpqUGJGTzgKLS0tIG5VeTJmTXRYcWVSK1RrUytMakN5
            MW5zNGRiYVllN3pOZ2ZWQlJjVUIzbTgKOiSoKja+wBKwKBqR6Zv8EZA4QBelqaFs
            ptppFxCi+KJNK2e0lsHRW4GzfPyL8m6SaP01UDn3TxXrwJHSkk41GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T09:43:46Z"
    mac: ENC[AES256_GCM,data:4/ZfLolEWxLbeC1iEabAFGnxtVbC4622mle1oXlg/HJFtXNXzQOsiGNhm1rm4S9eT53SZVOJopS177wMC8FY1P+1ULlcv2CzcydPAdNI5RzvmguEdb1P4jDd53nmvI4/Rdd5xgaUNfMUyzJqZ9Awwnu1uQ1Vau5QaeLe37I3pwc=,iv:NOr/MoGbEaHtIIr18DOx4YJaYP0Y1EjpgKuVQDlCQ9g=,tag:iBltvAUmtUt4uynuPE2xUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
