---
# Source: loadgenerator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
  labels:

    helm.sh/chart: loadgenerator-0.1.0
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/instance: loadgenerator
    app: loadgenerator
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: loadgenerator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    helm.sh/chart: loadgenerator-0.1.0
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/instance: loadgenerator
    app: loadgenerator
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgenerator
      app.kubernetes.io/instance: loadgenerator
      app: loadgenerator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadgenerator
        app.kubernetes.io/instance: loadgenerator
        app: loadgenerator
      annotations:
    spec:
      serviceAccountName: loadgenerator
      securityContext:
        {}
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: main
          securityContext:
            {}
          image: "gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.0"
          imagePullPolicy: IfNotPresent
          env:
          - name: FRONTEND_ADDR
            value: "frontend:80"
          - name: USERS
            value: "10"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
---
# Source: loadgenerator/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "loadgenerator-test-connection"
  labels:

    helm.sh/chart: loadgenerator-0.1.0
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/instance: loadgenerator
    app: loadgenerator
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['loadgenerator:80']
  restartPolicy: Never
