# resources/apps/keycloak/values.yaml


auth:
  adminUser: user
  adminPassword: user
image:
  repository: bitnamilegacy/keycloak
  tag: 26.3.1-debian-12-r2

postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql 
    tag: 17.6.0-debian-12-r4 
  volumePermissions:
    enabled: true
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  primary:
    podSecurityContext:
      fsGroup: 1001 
  auth:
    database: keycloak_db
    username: bn_keycloak
    password: epam_password


keycloakConfigCli:
  enabled: true
  image:
    repository: bitnamilegacy/keycloak-config-cli
    tag: 6.4.0-debian-12-r10
  configuration: 
    realm-epam.json: |
      {
        "realm": "EPAM-Internal",
        "enabled": true,
        "roles": {
          "realm": [
            { "name": "app-admin" },
            { "name": "app-viewer" }
          ]
        },
        "clients": [
          {
            "clientId": "portal-client",
            "enabled": true,
            "publicClient": true,
            "redirectUris": ["*"]
          }
        ]
      }