# resources/apps/keycloak/values.yaml

image:
  repository: bitnamilegacy/keycloak
  tag: 26.3.1-debian-12-r2

# Configuración de Vara (Postgres) con el fix de permisos
postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql 
    tag: 17.6.0-debian-12-r4 
  
  # ESTO ES LO QUE TE FALTA:
  volumePermissions:
    enabled: true  # Crea un contenedor temporal que arregla los permisos del disco
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r51
  
  primary:
    podSecurityContext:
      fsGroup: 1001 # Alinea el disco con el usuario de Bitnami
  
  auth:
    database: keycloak_db
    username: bn_keycloak
    password: epam_password

# Automatización del Config CLI
keycloakConfigCli:
  enabled: true
  configuration: 
    realm-epam.json: |
      {
        "realm": "EPAM-Internal",
        "enabled": true,
        "roles": {
          "realm": [
            { "name": "app-admin" },
            { "name": "app-viewer" }
          ]
        },
        "clients": [
          {
            "clientId": "portal-client",
            "enabled": true,
            "publicClient": true,
            "redirectUris": ["*"]
          }
        ]
      }