---
# Source: shippingservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  labels:

    helm.sh/chart: shippingservice-0.1.0
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app: shippingservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: shippingservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    helm.sh/chart: shippingservice-0.1.0
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app: shippingservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app: shippingservice
---
# Source: shippingservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    helm.sh/chart: shippingservice-0.1.0
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app: shippingservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shippingservice
      app.kubernetes.io/instance: shippingservice
      app: shippingservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shippingservice
        app.kubernetes.io/instance: shippingservice
        app: shippingservice
    spec:
      serviceAccountName: shippingservice
      securityContext:
        {}
      containers:
        - name: server
          securityContext:
            {}
          image: "gcr.io/google-samples/microservices-demo/shippingservice:v0.2.0"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"          
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]           
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
# Source: shippingservice/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "shippingservice-test-connection"
  labels:

    helm.sh/chart: shippingservice-0.1.0
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/instance: shippingservice
    app: shippingservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['shippingservice:50051']
  restartPolicy: Never
