spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: alpine:3.18
          command: ["sh", "-c"]
          args:
            - |
              set -e
              # Instalamos curl y tar para descargar los binarios
              apk add --no-cache curl tar
              # Descargamos SOPS (v3.9.4)
              curl -L https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64 -o /custom-tools/sops
              chmod +x /custom-tools/sops
              # Descargamos KSOPS (v4.3.1)
              mkdir -p /custom-tools/viaduct.ai/v1/ksops
              curl -L https://github.com/viaduct-ai/ksops/releases/download/v4.3.1/ksops_4.3.1_Linux_x86_64.tar.gz | tar -xz -C /custom-tools/viaduct.ai/v1/ksops ksops
              chmod +x /custom-tools/viaduct.ai/v1/ksops/ksops
          volumeMounts:
            - mountPath: /custom-tools
              name: ksops-plugin
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /app/config/sops/age/keys.txt
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/argocd/.config/kustomize/plugin
          volumeMounts:
            - mountPath: /home/argocd/.config/kustomize/plugin
              name: ksops-plugin
            - mountPath: /app/config/sops/age
              name: sops-age
      volumes:
        - name: ksops-plugin
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age