apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: viaductai/ksops:v4.3.1
          # CREAMOS LA ESTRUCTURA DE CARPETAS QUE PIDE EL ERROR
          command: ["sh", "-c", "mkdir -p /plugin/viaduct.ai/v1/ksops && cp /usr/local/bin/ksops /plugin/viaduct.ai/v1/ksops/ksops"]
          volumeMounts:
            - mountPath: /plugin
              name: ksops-plugin
      containers:
        - name: argocd-repo-server
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /app/config/sops/age/keys.txt
            - name: XDG_CONFIG_HOME
              value: /home/argocd/.config
          volumeMounts:
            # MONTAMOS EL PLUGIN EN LA RUTA QUE ARGO CD BUSCÓ EN TU ERROR
            - mountPath: /home/argocd/.config/kustomize/plugin
              name: ksops-plugin
            - mountPath: /app/config/sops/age
              name: sops-age
      volumes:
        - name: ksops-plugin
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age