---
# Source: redis-cart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart
  labels:
    helm.sh/chart: redis-cart-0.1.0
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/instance: redis-cart
    app: redis-cart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: redis-cart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    helm.sh/chart: redis-cart-0.1.0
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/instance: redis-cart
    app: redis-cart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/instance: redis-cart
    app: redis-cart
---
# Source: redis-cart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    helm.sh/chart: redis-cart-0.1.0
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/instance: redis-cart
    app: redis-cart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cart
      app.kubernetes.io/instance: redis-cart
      app: redis-cart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cart
        app.kubernetes.io/instance: redis-cart
        app: redis-cart
    spec:
      serviceAccountName: redis-cart
      securityContext:
        {}
      containers:
        - name: redis
          securityContext:
            {}
          image: "redis:alpine"
          imagePullPolicy: IfNotPresent
          ports:
          - name: redis
            containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          resources:
            limits:
              cpu: 125m
              memory: 256Mi
            requests:
              cpu: 70m
              memory: 200Mi
          volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
---
# Source: redis-cart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "redis-cart-test-connection"
  labels:
    helm.sh/chart: redis-cart-0.1.0
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/instance: redis-cart
    app: redis-cart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['redis-cart:6379']
  restartPolicy: Never
