apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

# ESTO ES LO QUE INVOCA A KSOPS PARA DESCIFRAR
generators:
  - ../../resources/apps/keycloak/secrets/keycloak-secrets.enc.yaml