apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # Añadimos la ruta al Secreto Sellado (4 niveles hacia arriba para llegar a la raíz)
  - ../../../../resources/apps/keycloak/secrets/keycloak-helm-sealedsecret.yaml