apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/raullopez1/mi-repo-gitops.git
    targetRevision: main
    path: manifests/apps/__overlays
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
