apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raullopezepam/mi-repo-gitops.git
    path: manifests/apps/__overlays
    targetRevision: main # ⚠️ Asegúrate de que tu rama se llame 'main' y no 'master'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # 👈 Importante: Las definiciones de apps viven en el namespace de Argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true