apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Todos los servicios del hipstershop - comenta/descomenta los que necesites deplorar
resources:
  - ../hipster-demo/adservice
  - ../hipster-demo/cartservice
  - ../hipster-demo/checkoutservice
  - ../hipster-demo/currencyservice
  - ../hipster-demo/emailservice
  - ../hipster-demo/frontend
  - ../hipster-demo/loadgenerator
  - ../hipster-demo/paymentservice
  - ../hipster-demo/productcatalogservice
  - ../hipster-demo/recommendationservice
  - ../hipster-demo/redis-cart
  - ../hipster-demo/shippingservice
