apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Todos los servicios del hipstershop - comenta/descomenta los que necesites deplorar
resources:
  - ../adservice
  - ../cartservice
  - ../checkoutservice
  - ../currencyservice
  - ../emailservice
  - ../frontend
  - ../loadgenerator
  - ../paymentservice
  - ../productcatalogservice
  - ../recommendationservice
  - ../redis-cart
  - ../shippingservice
