apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 15.5.2 # Versión de Chart estable
      helm:
        valueFiles:
          - $values/resources/apps/postgres/values.yaml
    - repoURL: https://github.com/raullopezepam/mi-repo-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-ns # El namespace independiente que querías
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true