apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  releaseName: frontend
  chart:
    spec:
      chart: ./charts/frontend # 👈 Apunta a tu carpeta local de charts
      sourceRef:
        kind: GitRepository
        name: flux-system # O el nombre de tu repo configurado en el controlador
        namespace: flux-system
  values:
    # Aquí puedes poner los mismos valores que tenías en el deployment
    image:
      repository: gcr.io/google-samples/microservices-demo/frontend
      tag: v0.2.0