apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: frontend
  # 🎯 Ruta correcta hacia donde están los planos del frontend
  path: ../../../../hipstershop-demo/helm/charts/frontend 
  releaseName: hipster-frontend
  # 🎯 Ruta correcta hacia tus valores personalizados
  valuesFile: ../../../../resources/hipstershop/values.yaml