apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: frontend
  releaseName: hipster-frontend
  # La ruta debe ser relativa al archivo kustomization.yaml
  path: ../../../../hipstershop-demo/helm/charts/frontend 
  valuesFile: ../../../../resources/hipstershop/values.yaml