---
# Source: cartservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
  labels:

    helm.sh/chart: cartservice-0.1.0
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app: cartservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: cartservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    helm.sh/chart: cartservice-0.1.0
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app: cartservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 7070
      name: grpc
  selector:
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app: cartservice
---
# Source: cartservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    helm.sh/chart: cartservice-0.1.0
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app: cartservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cartservice
      app.kubernetes.io/instance: cartservice
      app: cartservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cartservice
        app.kubernetes.io/instance: cartservice
        app: cartservice
    spec:
      serviceAccountName: cartservice
      securityContext:
        {}
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            {}
          image: "gcr.io/google-samples/microservices-demo/cartservice:v0.2.0"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 7070
          env:
          - name: REDIS_ADDR
            value: "redis-cart:6379"
          - name: PORT
            value: "7070"
          - name: LISTEN_ADDR
            value: "0.0.0.0"          
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
          readinessProbe:
            initialDelaySeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi
---
# Source: cartservice/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "cartservice-test-connection"
  labels:

    helm.sh/chart: cartservice-0.1.0
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/instance: cartservice
    app: cartservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['cartservice:7070']
  restartPolicy: Never
